mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://127.0.0.1
  user: hass
  password: dummY
homeassistant:
  enabled: true
serial:
  port: /dev/ttyACM0
frontend:
  enabled: true
  port: 8080
advanced:
  network_key:
    - 205
    - 230
    - 123
    - 1
    - 53
    - 33
    - 149
    - 194
    - 0
    - 57
    - 131
    - 35
    - 117
    - 156
    - 105
    - 154
  log_level: warning
  last_seen: ISO_8601
  transmit_power: 127
devices:
  '0xa4c138aa6a05118d':
    friendly_name: Stecker 2
    power_precision: 2
    voltage_precision: 2
    current_precision: 2
    energy_precision: 2
  '0x00158d0008d8e15f':
    friendly_name: Bewegungsmelder Haustür
    device_temperature_calibration: -9
    occupancy_timeout: 30
    illuminance_lux_calibration: ''
    illuminance_calibration: ''
  '0xa4c138d64ce6279f':
    friendly_name: Haustür Lampe 1
  '0xa4c138edecb090d8':
    friendly_name: Haustür Lampe 2
  '0xa4c13808bc858057':
    friendly_name: Garagenlampe 1
  '0xa4c1386273190b5b':
    friendly_name: 'Bewegungsmelder Garage '
    occupancy_timeout: 60
  '0xa4c138676e381225':
    friendly_name: 'Gartenpumpe '
  '0x000d6f00101cd775':
    friendly_name: 'Leo Licht Fernbedienung '
  '0xa4c138f8635aefcd':
    friendly_name: 'Solarheizung '
    power_calibration: 0
    measurement_poll_interval: ''
    current_calibration: 0
    energy_calibration: 0
    voltage_calibration: 0
  '0x804b50fffee0efe1':
    friendly_name: 'Steckerleiste '
  '0xa4c138b9d085911c':
    friendly_name: Bewegungsmelder Gartenhaus
  '0xa4c138a948c281a7':
    friendly_name: Leos Lampe
  '0xa4c13878aad5d7a1':
    friendly_name: BueroStecker
  '0xa4c138318aad9ff1':
    friendly_name: GartenhausPV
  '0x00158d00031d2a62':
    friendly_name: GartenhausLampe
  '0xa4c138991960f8e6':
    friendly_name: Weihnachtsbaum
  '0xa4c138dc6de95b53':
    friendly_name: 'Lichterkette Küche '
  '0xa4c138c393eecf57':
    friendly_name: Buero2
    measurement_poll_interval: 60
  '0x180df9fffe840d72':
    friendly_name: Rolläden Nähzimmer
  '0x00124b0029295963':
    friendly_name: Kellertemp Heizung
  '0x385cfbfffec544c4':
    friendly_name: Nässesensor Heizkeller
  '0x206ef1fffe05055c':
    friendly_name: Rolläden Kinderzimmer
  '0x206ef1fffe017194':
    friendly_name: Rolläden Badezimmer
  '0x20a716fffe41b48e':
    friendly_name: Rolläden Spielzimmer
  '0xc09b9efffed13e14':
    friendly_name: Rolläden Arbeitszimmer
  '0xccba97fffeefa274':
    friendly_name: Rolläden Küche
  '0x00124b0029294c0a':
    friendly_name: Kellertemp
  '0xccba97fffeef99e4':
    friendly_name: Rolläden Sofa
  '0xccba97fffeef99f0':
    friendly_name: Rolläden Essecke
  '0xccba97fffeef8b5c':
    friendly_name: Rolläden Terrasse
  '0xd885acfffee9107c':
    friendly_name: Nässesensor Keller
  '0xc09b9efffeeee3c9':
    friendly_name: Rolläden Schlafzimmer
groups: {}
version: 5
availability:
  enabled: true
