- id: '1675612618800'
  alias: 'Haustür Bewegungsmelder '
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.bewegungsmelder_haustur_occupancy
      light_switch:
        entity_id:
        - light.haustur_lampe_1
        - light.haustur_lampe_2
      ambient_light_sensor: sensor.bewegungsmelder_haustur_illuminance_lux
      ambient_light_options: ambient_light_option_disabled
      time_delay: 1
      include_light_control: use_brightness
      include_ambient: ambient_enabled
      ambient_light_value: 90
      include_sun: sun_enabled
      sun_elevation: 0
- id: '1677505658484'
  alias: 'Garagenlicht Bewegungsmelder '
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.bewegungsmelder_garage_occupancy
      ambient_light_sensor: sensor.bewegungsmelder_haustur_illuminance_lux
      ambient_light_options: ambient_light_option_disabled
      time_delay: 1
      include_light_control: use_brightness
      include_ambient: ambient_enabled
      ambient_light_value: 120
      light_switch:
        device_id: 326b48d4842bd6579edde4ce6988419e
      include_sun: sun_enabled
      sun_elevation: 0
- id: '1678299190989'
  alias: Send Notification
  trigger:
  - platform: numeric_state
    entity_id: sensor.hum_abs_keller
    above: sensor.hum_abs_outside
  condition:
  - condition: numeric_state
    entity_id: sensor.hum_abs_keller
    above: sensor.hum_abs_outside
  - condition: numeric_state
    entity_id: sensor.kellertemp_humidity
    attribute: humidity
    above: 60
  action:
  - service: notify.mobile_app_pixel_6
    data:
      message: Keller lüften wäre jetzt cool...
      title: Keller
- id: '1684942536663'
  alias: Leo Licht an aus
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 15b7db31564d7217ef73154a7e933a79
    type: action
    subtype: circle_click
    discovery_id: 0x000d6f00101cd775 action_circle_click
  condition: []
  action:
  - type: toggle
    device_id: 74b5e98613794d8c4f1335f3acb0e00f
    entity_id: light.leos_lampe
    domain: light
  mode: single
- id: '1684945772411'
  alias: 'Leo Licht heller '
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 15b7db31564d7217ef73154a7e933a79
    type: action
    subtype: up
    discovery_id: 0x000d6f00101cd775 action_up
  condition: []
  action:
  - device_id: 74b5e98613794d8c4f1335f3acb0e00f
    domain: light
    entity_id: light.leos_lampe
    type: brightness_increase
  mode: single
- id: '1684945893990'
  alias: 'Leo Licht dunkler '
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 15b7db31564d7217ef73154a7e933a79
    type: action
    subtype: down
    discovery_id: 0x000d6f00101cd775 action_down
  condition: []
  action:
  - device_id: 74b5e98613794d8c4f1335f3acb0e00f
    domain: light
    entity_id: light.leos_lampe
    type: brightness_decrease
  mode: single
- id: '1698329760687'
  alias: 'Inverter einschalten '
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: -01:00:00
  condition: []
  action:
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: sensor.soyo_power_demand
      for:
        hours: 0
        minutes: 0
        seconds: 0
      above: 0
    timeout:
      hours: 4
      minutes: 0
      seconds: 0
      milliseconds: 0
  - repeat:
      sequence:
      - type: turn_on
        device_id: 7c261a60cb0dd9f9f4e79f728d8524d3
        entity_id: 8cca7c1e062ad863f4a8ef4f1e284c56
        domain: switch
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      until:
      - condition: state
        entity_id: switch.stecker_2
        state: 'on'
  mode: single
- id: '1698329979950'
  alias: 'Inverter ausschalten '
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition:
  - condition: numeric_state
    entity_id: sensor.soyo_power
    below: 2
  action:
  - repeat:
      sequence:
      - type: turn_off
        device_id: 7c261a60cb0dd9f9f4e79f728d8524d3
        entity_id: 8cca7c1e062ad863f4a8ef4f1e284c56
        domain: switch
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      until:
      - condition: state
        entity_id: switch.stecker_2
        state: 'off'
  mode: single
- id: '1699372497889'
  alias: 'Gartenhaus Bewegungsmelder '
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.bewegungsmelder_gartenhaus_occupancy
      ambient_light_sensor: sensor.bewegungsmelder_haustur_illuminance_lux
      ambient_light_options: ambient_light_option_disabled
      time_delay: 2
      include_light_control: use_brightness
      include_ambient: ambient_enabled
      ambient_light_value: 190
      light_switch:
        entity_id:
        - light.gartenhauslampe
      include_sun: sun_enabled
      sun_elevation: 1
- id: '1712585051298'
  alias: Strompreis hoch
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.***REMOVED***_strompreis
    above: 0.3
  condition: []
  action:
  - type: turn_on
    device_id: 4aa3fe777c6e7ab927681f22403d1c8e
    entity_id: cc555d3977f22d6b46b4bd50e25f08e3
    domain: switch
  - type: turn_off
    device_id: 4aa3fe777c6e7ab927681f22403d1c8e
    entity_id: 1fb3fc353abb9ba067c9f31679ac738a
    domain: switch
  mode: single
- id: '1712585167918'
  alias: Strompreis ok
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.***REMOVED***_strompreis
    below: 0.28
  - platform: numeric_state
    entity_id:
    - sensor.***REMOVED***_strompreis
    above: 0.2
  condition: []
  action:
  - type: turn_off
    device_id: 4aa3fe777c6e7ab927681f22403d1c8e
    entity_id: cc555d3977f22d6b46b4bd50e25f08e3
    domain: switch
  - type: turn_off
    device_id: 4aa3fe777c6e7ab927681f22403d1c8e
    entity_id: 1fb3fc353abb9ba067c9f31679ac738a
    domain: switch
  mode: single
- id: '1712585326909'
  alias: Strompreis niedrig
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.***REMOVED***_strompreis
    below: 0.18
  condition:
  - type: is_battery_level
    condition: device
    device_id: 4aa3fe777c6e7ab927681f22403d1c8e
    entity_id: 38777fed0f725b8ac3776036351ae205
    domain: sensor
    below: 65
  action:
  - type: turn_off
    device_id: 4aa3fe777c6e7ab927681f22403d1c8e
    entity_id: cc555d3977f22d6b46b4bd50e25f08e3
    domain: switch
  - type: turn_on
    device_id: 4aa3fe777c6e7ab927681f22403d1c8e
    entity_id: 1fb3fc353abb9ba067c9f31679ac738a
    domain: switch
  - device_id: 4aa3fe777c6e7ab927681f22403d1c8e
    domain: number
    entity_id: 91eadeddacef5e14eb747595b1cef699
    type: set_value
    value: 0
  mode: single
