
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate


automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml

counter:
  gaszaehler:
    initial: 0
    step: 1

recorder:
  purge_keep_days: 10
  db_url: postgresql://hass:hassPw321@127.0.0.1/smart_home
  commit_interval: 60
  include:
    domains:
      #      - person
      - sensor
      - binary_sensor
      - light
      - switch
      - lock
      - sql
      - cover
      - automation
      #      - update
    entity_globs:
      - sensor.jk_bms_cell_voltage_*
      - sensor.jk_bms_temperature_sensor_*
    entities:
      - sensor.jk_bms_total_voltage
      - sensor.jk_bms_charging_power
      - sensor.jk_bms_discharging_power
      - sensor.jk_bms_power
      - sensor.jk_bms_charging_energy_today
      - sensor.jk_bms_discharging_energy_today
      - sensor.jk_bms_actual_battery_capacity
        #      - sensor.jk_bms_balancing
      - sensor.jk_bms_capacity_remaining
      - sensor.jk_bms_charging_cycles
      - sensor.jk_bms_current
      - sensor.jk_bms_bms_temperature
      - sensor.jk_bms_state_of_charge
      - sensor.jk_bms_delta_cell_voltage
      - sensor.openwathermap_humidity
      - sensor.openwathermap_temperature
      - sensor.openwathermap_pressure
     
  exclude:
    entity_globs:
      - sensor.jk_bms*
      - sensor.openweather
      - sensor.tibber_pulse_*_energie
      - sensor.tibber_pulse_*_stromerzeugung
    entities:
      - sensor.power_consumption
      - sensor.soyo_power_demand


homeassistant:
  allowlist_external_dirs:
    - /Recordings
  customize_glob:
    sensor.total_energy_in:
      last_reset: 2023-01-01T00:00:00+00:00
    sensor.total_energy_out:
      last_reset: 2023-01-01T00:00:00+00:00
    sensor.gasverbrauch_m3:
      state_class: total_increasing
    sensor.gasverbrauch_kwh:
      state_class: total_increasing

http:
  use_x_forwarded_for: true
  trusted_proxies: 10.9.8.1

lovelace:
  resources:
    - url: /local/apexcharts-card.js?v=2.1.2
      type: module


template:
  - trigger:
      - platform: time_pattern
        minutes: '/1'
    sensor:
      - name: tibber_preis_jetzt
        state: >-
          {% set preise = state_attr('sensor.tibber_preis', 'today') %}
          {{ preise | selectattr('startsAt', 'ge', utcnow().isoformat()) | sort(attribute = 'startsAt') | map(attribute='total') | first }}
        unit_of_measurement: €/kWh
        device_class: monetary
        icon: mdi:currency-eur
        unique_id: tibber_preis_jetzt


