# Enable logging
logger:
  baud_rate: 0
  level: INFO

# Enable Home Assistant API
api:
  password: ""
  batch_delay: 25ms

ota:
  platform: esphome
  password: ""

captive_portal:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw
  manual_ip:
    static_ip: 192.168.1.21
    gateway: 192.168.1.1
    subnet: 255.255.255.0

mqtt:
 id: mqttclient 
 broker: 192.168.1.25
 username: hass
 password: dummY
 reboot_timeout: "0s"
   # topic_prefix: smartmeter

esphome:
  name: smartmeter
  comment: "Smartmeter"

esp8266:
  board: esp01_1m
  restore_from_flash: false
preferences:
  flash_write_interval: 60min


    #external_components:
    #  - source: github://alengwenus/esphome_components@main
    #    refresh: 0s
    #    components: [sml]

uart:
  id: uart_bus
  tx_pin: GPIO01
  rx_pin: GPIO03
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 512

sml:
  id: mysml
  uart_id: uart_bus
  on_data:
    - lambda: !lambda |-
        if (valid) {
          id(mqttclient).publish("smartmeter/sensor/sml/state", format_hex(bytes));
        }

sensor:
  - platform: sml
    name: "Total energy out"
    state_topic:
    sml_id: mysml
    obis_code: "1-0:2.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.0001
      - throttle: 300s

  - platform: sml
    sml_id: mysml
    name: "Total energy in"
    state_topic:
    obis_code: "1-0:1.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.0001
      - throttle: 300s

  - platform: sml
    name: "power consumption"
    sml_id: mysml
    state_topic:
    icon: "mdi:lightning-bolt"
    obis_code: "1-0:16.7.0"
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: power
    state_class: measurement


      #  - platform: pulse_counter
      #    pin: 
      #      number: GPIO00
#      mode: INPUT_PULLUP
#    name: "Gasverbrauch"
#    update_interval : 60s
#    internal_filter: 100ms
#    filters:
#      - lambda: |-
#          static float total_value = 0.0;
#          total_value += x * 0.01;
#          return total_value;
#    unit_of_measurement: "m³"
#    accuracy_decimals: 2
#    icon: 'mdi:fire'


